version: '3.4'

services:
  webapplicationshowlogging:
    image: ${DOCKER_REGISTRY-}webapplicationshowlogging
    build:
      context: .
      dockerfile: WebApplicationShowLogging/Dockerfile
    ports:
      - "3099:80"
    networks:
      - backend-demo

  # LOGGER
  demo.seq:
    image: datalust/seq:latest
    container_name: seqDemo
    ports:
      - "5343:80"
    environment:
      ACCEPT_EULA: "Y"
    restart: unless-stopped
    volumes:
      - seq-data:/data
    networks:
      - backend-demo

  #ELK
  demo.elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearchDemo
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node   
      ELASTIC_PASSWORD: "KXjnP*zPjJyp0hUw4yoQ"
      xpack.security.enabled: "true"
      xpack.security.enrollment.enabled: "true" 
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - backend-demo

  #gms.logstash:
  #  image: logstash:7.16.2
  #  container_name: gmslogstash
  #  restart: always
  #  volumes:
  #  - ./logstash/:/logstash_dir
  #  command: logstash -f /logstash_dir/logstash.conf 
  #  depends_on:
  #    - gms.elasticsearch
  #  ports:
  #  - '9600:9600'
  #  environment:
  #    LS_JAVA_OPTS: "-Xmx256m -Xms256m"    
  #  networks:
  #    - elk

  demo.kibana:
    image: kibana:8.12.0
    container_name: kibanaDemo
    restart: always       
    ports:
    - '9900:5601'
    environment:
      ELASTICSEARCH_URL: "http://elasticsearchDemo:9200"
    depends_on:
      - demo.elasticsearch  
    networks:
      - backend-demo

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.12.0
    container_name: apmDemo
    cap_add: ["CHOWN", "DAC_OVERRIDE", "SETGID", "SETUID"]
    cap_drop: ["ALL"]
    ports:
    - 8200:8200
    command: >
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=kibanaDemo:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=kibana:5601
         -E output.elasticsearch.hosts=["elasticsearchDemo:9200"]
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/
    networks:
      - backend-demo

volumes:
  seq-data:
  elastic_data: {}

networks:
  backend-demo:
